### ISSUE TITLE
Contao 4.6.13: overwriting files leads to deletion on sync

### ISSUE THREAD

**Issue by johannes-bittner** [heimrichhannot/contao-filename-sanitizer-bundle#3]
As stated here [(https://github.com/heimrichhannot/contao-upload_filename_sanitizer/issues/5):](https://github.com/heimrichhannot/contao-upload_filename_sanitizer/issues/5) If you upload a file with the same file name in the file explorer in a given directory, the existing file should simply be overwritten and the UUID should stay the same. With contao-upload_filename_sanitizer installed, I was able to reproduce the following behavior:

- upload document testdoc.txt: existing document testdoc.txt gets overwritten
- execute sync outputs the message: testdoc.txt was deleted
- nevertheless, testdoc.txt still exists in the give directory, but links to that file are broken (e.g. for downloads, other extension assets, linked images etc.)

**Comment by Defcon0** [comment]
Should be fixed in https://github.com/heimrichhannot/contao-filename-sanitizer-bundle/tree/1.1.2 . Could you please check if the error persists?

Unlike your description I assumed that you tried to upload a file with name `testÄdoc.txt` where another file with the name `test-doc.txt` already existed since this situation was the only one which didn't work in my tests.

I also fixed the issue for folders.

**Comment by koertho** [comment]
@johannes-bittner Can you report back? Otherwise we will close this issue soon.

**Comment by johannes-bittner** [comment]
Fixed for me with Version 1.3.1 and Contao 4.7.7

**Comment by koertho** [comment]
@johannes-bittner Thanks!
